socialhub/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('create/', views.post_create, name='post_create'),
    path('create-comment/<int:pk>', views.comment_create, name='comment_create'),
    path('detail/<int:pk>', views.post_detail, name='post_detail'),
    path('delete/<int:pk>', views.post_delete, name='post_delete'),
    path('update/<int:pk>', views.post_update, name='post_update'),
    path('comment_like/', views.comment_like, name='comment_like'),
    path('like/', views.post_like, name='like'),

]

socialhub/profiles/urls.py
from django.urls import path
from . import views

app_name = 'prof'

urlpatterns = [
    path('', views.profile_view, name='myprofile'),
    path('<int:pk>/', views.pk_profile, name='pk_profile'),
    path('update/<int:pk>/', views.update_profile, name='update_profile'),
]

socialhub/socialhub/urls.py
from django.contrib import admin
from django.urls import path, include
from post import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('profile/', include('profiles.urls', namespace='prof')),
    path('post/', include('post.urls', namespace='post')),
    path('', views.redirect_to_post)
]

socialhub/post/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    title = models.CharField(max_length=256, blank=True)
    text = models.TextField(blank=True)
    published = models.DateTimeField(auto_now=True)
    like = models.ManyToManyField(User, related_name='like', blank=True)
    like_bool = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        indexes = [
            models.Index(fields=['-published'])
        ]


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField(blank=True)
    like = models.ManyToManyField(User, related_name='like_comment', blank=True)
    published = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.post)

    class Meta:
        indexes = [
            models.Index(fields=['-published'])
        ]

socialhub/post/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text']


class PostFormCreate(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['id', 'title', 'text']


class CommentFormCreate(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['id', 'text']

socialhub/post/views.py
import redis
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from django.contrib.auth.decorators import login_required
from .forms import PostForm, PostFormCreate, CommentFormCreate
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.http import require_POST


@login_required
def post_list(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, 'post/post_list.html', context)


@login_required
def post_update(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.user == request.user:
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                post.title = request.POST.get('title')
                post.text = request.POST.get('text')
                post.save()
                return HttpResponseRedirect('/post/')
        else:
            form = PostForm()
    else:
        return HttpResponse('Вы не автор этого поста!!')
    return render(request, 'profiles/update.html', {"form": form})


r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB)


@login_required
def post_detail(request, pk):
    user = request.user
    post = get_object_or_404(Post, pk=pk)
    total_views = r.incr(f'post:{post.id}:views')

    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=post)
    return render(request, 'post/detail.html',
                  {'post': post, 'user': user, 'total_views': total_views, 'comments': comments})


@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.user == request.user:
        post.delete()
    else:
        return HttpResponse('Вы не автор этого поста!!')
    return HttpResponseRedirect('/post/')


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostFormCreate(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return HttpResponseRedirect('/post/')
    form = PostFormCreate()
    return render(request, 'post/create.html', {'form': form})


def redirect_to_post(request):
    return HttpResponseRedirect('/post/')


@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    if post_id and action:
        try:
            post = Post.objects.get(id=post_id)
            if request.user not in post.like.all():
                post.like.add(request.user)
            else:
                post.like.remove(request.user)

            return JsonResponse({'status': 'ok'})
        except Post.DoesNotExist:
            pass
        return JsonResponse({'status': 'error'})


def comment_create(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentFormCreate(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.instance.post = post
            form.save()
            return redirect('post:post_detail', post.pk)
    form = CommentFormCreate()
    return render(request, 'post/comment_create.html', {'form': form})


def comment_like(request):
    pass
    # TODO создать отдельную html-страницу и п уже перенести его в основной(include)

socialhub/post/templates/post/comment_create.html
{% extends 'base.html' %}

{% block content %}
    <h1>New Comment</h1>
    <form method="POST" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

socialhub/post/templates/post/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

socialhub/post/templates/post/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>Delete Post?</p>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

socialhub/post/templates/post/detail.html
{% extends "base.html" %}

{% block title %}Post{% endblock %}


{% block content %}
  <h1>My Post</h1>

  <h1>{{ post.user.username }}</h1>
  <p>{{ post.title }}</p>
  <p>{{ post.text }}</p>

  {% if post.user == request.user %}
    <p><a href="{% url 'post:post_update' post.pk %}">Update Post</a></p>
    <p><a href="{% url 'post:post_delete' post.pk %}">Delete Post</a></p>
  {% endif %}

  <hr>
    {% with users_like=post.like.all %}

    <a href="#" data-id="{{ post.id }}" data-action="{% if request.user in like %}un{% endif %}like" class="like button">
        {% if request.user not in users_like %}
          Like
        {% else %}
          Unlike
        {% endif %}
    </a>
    {{ post.like.count }}
    {{ n }}
    <p>{{ total_views }} views</p>
  {% endwith %}
  <hr>
  <p><a href="{% url 'post:comment_create' post.pk %}">Create comment</a></p>
  {% for comment in comments %}
    <p>{{ comment.user }}</p>
    <p>{{ comment.text }}</p>
    <br>
    <hr>
  {% endfor %}
{% endblock %}


{% block domready %}
  const url = '{% url "post:like" %}';
  var options = {
    method: 'POST',
    headers: {'X-CSRFToken': csrftoken},
    mode: 'same-origin'
  }

  document.querySelector('a.like')
          .addEventListener('click', function(e){
    e.preventDefault();
    var likeButton = this;

    var formData = new FormData();
    formData.append('id', likeButton.dataset.id);
    formData.append('action', likeButton.dataset.action);
    options['body'] = formData;

    fetch(url, options)
    .then(response => response.json())
    .then(data => {
      if (data['status'] === 'ok')
      {
      }
    })
  });
{% endblock %}

socialhub/post/templates/post/post_list.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
  <h1>Посты</h1>
  {% for post in posts %}
    <a href="{% url 'prof:pk_profile' post.user.pk %}">{{ post.user.profile.pk }}</a>
    <p><a href="{% url 'post:post_detail' post.pk %}">{{ post.pk }}</a></p>
    <hr>
  {% endfor %}
{% endblock %}