socialhub/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('create/', views.post_create, name='post_create'),
    path('create-comment/<int:pk>', views.comment_create, name='comment_create'),
    path('detail/<int:pk>', views.post_detail, name='post_detail'),
    path('delete/<int:pk>', views.post_delete, name='post_delete'),
    path('update/<int:pk>', views.post_update, name='post_update'),
    path('comment_like/', views.comment_like, name='comment_like'),
    path('like/', views.post_like, name='like'),

]

socialhub/profiles/urls.py
from django.urls import path
from . import views

app_name = 'prof'

urlpatterns = [
    path('', views.profile_view, name='myprofile'),
    path('<int:pk>/', views.pk_profile, name='pk_profile'),
    path('update/<int:pk>/', views.update_profile, name='update_profile'),
]

socialhub/socialhub/urls.py
from django.contrib import admin
from django.urls import path, include
from post import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('profile/', include('profiles.urls', namespace='prof')),
    path('post/', include('post.urls', namespace='post')),
    path('', views.redirect_to_post)
]

socialhub/profiles/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=256, blank=True)
    last_name = models.CharField(max_length=256, blank=True)
    bio = models.TextField(default='no bio.', blank=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name

    class Meta:
        ordering = ['-created']

socialhub/profiles/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'bio']

socialhub/profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from post.models import Post
from django.contrib.auth.models import User
from .models import Profile
from django.http import HttpResponseRedirect
from .forms import ProfileForm


@login_required
def profile_view(request):
    profile = request.user.profile
    posts = Post.objects.filter(user=request.user)
    return render(request, 'profiles/myprofile.html', {'profile': profile,
                                                                           'posts': posts})


@login_required
def pk_profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    posts = Post.objects.filter(user=user)
    context = {'posts': posts, 'user': user}
    return render(request, 'profiles/pkprofile.html', context)


def update_profile(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile.first_name = request.POST.get('first_name')
            profile.last_name = request.POST.get('last_name')
            profile.bio = request.POST.get('bio')
            profile.save()
            return HttpResponseRedirect('/profile/')
    else:
        form = ProfileForm()
    return render(request, 'profiles/update.html', {"form": form})

socialhub/profiles/templates/profiles/myprofile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
  <h1>My Profile</h1>

  {{ profile.last_name }}
  {{ profile.first_name }}
  <p>{{ profile.user }}</p>

  <p>{{ profile.bio }}</p>
  <a href="{% url 'prof:update_profile' profile.pk %}">Update Profile</a>
<!--  <a href="{% url 'prof:pk_profile' profile.pk %}">Update Profile</a>-->
  <a href="{% url 'post:post_create' %}">Create Post</a>

  <br>
  <hr>
{% for post in posts %}
    {{ post.title }}
  {% endfor %}
{% endblock %}

socialhub/profiles/templates/profiles/pkprofile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
  <h1>My Profile</h1>


  {{ user.profile.last_name }}
  {{ user.profile.first_name }}
  <p>{{ user.profile.user }}</p>
  <p>{{ user.profile.bio }}</p>


  <br>
  <hr>

  {% for post in posts %}
    {{ post.title }}
  {% endfor %}

{% endblock %}

socialhub/profiles/templates/profiles/update.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
  <h1>Update Profile</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}